Homework
CodeMasteryCraft/PetFamily pull request #40
Opened 2024-05-12 16:37 UTC by SonicMusic

2024-05-12 16:58 UTC, KirillSachkov requested changes

2024-05-12 16:58 UTC, KirillSachkov commented on PetFamily.Application/Features/Volunteers/DeletePhoto/DeleteVolunteerPhotoHandler.cs
> +        var volunteer = await _volunteersRepository.GetById(request.VolunteerId, ct);
Волонтёру нужно добавить метод для удаления фото в модели, по аналогии с добавлением. Ты из базы данных получаешь волонтера и сразу коллекцию его фото, там нужно удалить из колекции фото и сохранить модель в бд

2024-05-12 16:58 UTC, KirillSachkov commented on PetFamily.Application/Features/Volunteers/GetPhoto/GetAllVolunteerPhotoHandler.cs
> +    public async Task<Result<IReadOnlyList<string>, Error>> Handle(GetAllVolunteerPhotoRequest request, CancellationToken ct)
Мы используем подход CQRS, разделение на чтение и создание данных. Для чтения мы создаём классы query и используем там PetFamilyReadContext, то есть контекст для чтения. Там нужно все эти операции проделывать

2024-05-13 11:25 UTC, SonicMusic commented on PetFamily.Application/Features/Volunteers/DeletePhoto/DeleteVolunteerPhotoHandler.cs
> +        var volunteer = await _volunteersRepository.GetById(request.VolunteerId, ct);
у меня получилось, что фото из коллекции волонтёра удалилось, но из БД не удалилось
![2024-05-13_15-24-30](https://github.com/CodeMasteryCraft/PetFamily/assets/116547812/0ce314ce-47f2-4565-bda1-37e85f311400)

2024-05-13 11:57 UTC, KirillSachkov commented on PetFamily.Infrastructure/Queries/Volunteers/GetPhoto/GetAllVolunteerPhotoHandler.cs
> +public class GetAllVolunteerPhotoHandler
Этот класс должен называться GetAllVolunteerPhotosQuery. Нам не нужен отдельный query класс для волонтера. У нас каждый класс - это запрос на получение всех нужных данных. То есть мы в этом классе можем использовать readdbcontext, потому что мы в проекте с инфраструктурой. То есть ты прямо здесь достаешь с dbcontext волонтера и его все фотки и дальше уже с ними делаешь, что нужно

2024-05-13 11:57 UTC, KirillSachkov commented on PetFamily.Infrastructure/Queries/Volunteers/GetPhoto/GetAllVolunteerPhotoHandler.cs
> +        var volunteerDto = await _volunteersQuery.GetById(request.VolunteerId, ct);
это не нужно, вместо этого сразу тут используй dbcontext

2024-05-13 11:57 UTC, KirillSachkov commented on PetFamily.Infrastructure/Queries/Volunteers/VolunteersQuery.cs
> +public class VolunteersQuery : IVolunteersQuery
убрать этот класс

2024-05-13 11:57 UTC, KirillSachkov commented on PetFamily.Infrastructure/DbContexts/PetFamilyReadDbContext.cs
> +public class PetFamilyReadDbContext : DbContext, IPetFamilyReadDbContext
это не нужно, мы этот dbcontext используем только в рамках этого проекта

2024-05-13 17:32 UTC, KirillSachkov approved these changes

2024-05-13 17:32 UTC, merged