add getpet
CodeMasteryCraft/PetFamily pull request #60
Opened 2024-06-09 17:01 UTC by SonicMusic

2024-06-11 13:04 UTC, KirillSachkov requested changes

2024-06-11 13:04 UTC, KirillSachkov commented on PetFamily.Infrastructure/Queries/Pets/GetPetQuery.cs
> +        var petDto = new PetDto(pet.Id, pet.Nickname, pet.Description, pet.BirthDate, pet.Breed, pet.Color,
Можно сделать метод расширения для PetDto для маппинга из PetReadModel на PetDto

2024-06-11 13:04 UTC, KirillSachkov commented on PetFamily.Infrastructure/Queries/Volunteers/GetPets/GetVolunteerPetsQuery.cs
> +        var volunteer = await _readDbContext.Volunteers
Лучше по-другому построить запрос. Лучше получить всех животных у которых VolunteerId будет равен твоего volunteerId.

2024-06-11 13:04 UTC, KirillSachkov commented on PetFamily.Infrastructure/Queries/Volunteers/GetPets/GetVolunteerPetsQuery.cs
> +        var pets = volunteer.Pets.Select(pet => new PetDto(
и здесь можно использовать метод расширения

2024-06-16 08:47 UTC, SonicMusic commented on PetFamily.Application/Dtos/PetDto.cs
> +    List<PetPhotoDto> Photos,
тогда в 
PetFamily.Infrastructure/Queries/Pets/GetAllPetsQuery.cs 
возникает ошибка вот здесь
pet.Photos.Add(photo);

2024-06-16 08:54 UTC, SonicMusic commented on PetFamily.Infrastructure/Queries/Pets/GetPetQuery.cs
> +        var petDto = new PetDto(pet.Id, pet.Nickname, pet.Description, pet.BirthDate, pet.Breed, pet.Color,
как маппинг сделать не понял

2024-06-16 09:20 UTC, SonicMusic commented
fix

2024-06-16 10:25 UTC, KirillSachkov requested changes

2024-06-16 10:25 UTC, KirillSachkov commented on PetFamily.Infrastructure/ReadModels/PetReadModel.cs
> +    public Address Address { get; private set; } = null!;
Вместо valu object должны быть свойства

2024-06-16 11:32 UTC, SonicMusic commented on PetFamily.Infrastructure/Queries/Pets/GetByIdPetQuery.cs
> +        var pet = await _readDbContext.Pets.Include(petReadModel => petReadModel.Address).FirstOrDefaultAsync(p => p.Id == request.PetId, cancellationToken: ct);
эти инклуды не помню чтобы я их делал
походу райдер их добавил

2024-06-16 13:55 UTC, merged